services:
  plasmo-repo:
    container_name: plasmo-repo
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - "..:/home"
    command: [ "sleep", "infinity" ]
